### ISSUE TITLE
Notes on WordPress updates screen feature request

### ISSUE THREAD

**Issue by douglsmith** [jamiebergen/plugin-notes-plus#1]
I'd like to suggest the feature of also showing the notes on the WordPress updates screen.

Here's my use case. I have a plugin that was recently updated and the new version breaks my site. I rolled back to the prior version and added a note about the situation to the plugin. But if another admin decides to apply updates through the update screen it is possible that will happen without ever seeing the note.

**Comment by jamiebergen** [comment]
I completely agree! I previously looked into this, but WordPress doesn't provide the same hooks on the update screen as it does on the plugins page. But I'll revisit this at some point when I have some time because it's a valid request.

**Comment by jamiebergen** [comment]
I added this feature in version 1.2.0. Thanks for the suggestion!
