### ISSUE TITLE
Move language files to translate.wordpress.org

### ISSUE THREAD

**Issue by ramiy** [jamiebergen/plugin-notes-plus#12]
@jamiebergen 

You should delete all the PO/MO files from the plugin. All the translation strings should be uploaded to https://translate.wordpress.org/projects/wp-plugins/plugin-notes-plus/ . This way the plugin stays small and efficient.

WordPress will automatically download the language files. And only the languages used by the site, not all the languages.

WP Core has a cron job every 12 hours. It check for core/plugins/themes updates. In adittion it check for new translation strings. If some plugin have new strings, WordPress will download the PO/MO files to `/wp-content/languages/plugins/`

**Comment by jamiebergen** [comment]
@ramiy 

Thank you! I've removed the PO/MO files and released a new version of the plugin.
