### ISSUE TITLE
Abandoned plugin?

### ISSUE THREAD

**Issue by Manja-S** [jamiebergen/plugin-notes-plus#17]
On its [official page](https://nl.wordpress.org/plugins/plugin-notes-plus/), the following warning can be found:
"This plugin has not been tested with the latest 3 larger versions of WordPress. It may no longer be maintained or supported. There may also be compatibility issues when used with more recent versions of WordPress."

Has this (very useful) plugin been abandoned?

**Comment by jamiebergen** [comment]
Not abandoned.

**Comment by Manja-S** [comment]
@jamiebergen  A year has passed, and there's still this message at https://wordpress.org/plugins/plugin-notes-plus/: "This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress." 

I would really hate it if WordPress were to withdraw this plugin. Can I help you with anything to avoid that?

**Comment by BrianHenryIE** [comment]
AIUI, WordPress.org does not withdraw plugins. 

Unless you have a specific concern about this plugin, your comment is worthless. 

The plugin works well and your failure to understand is not a reflection on the quality of the plugin.

**Comment by Manja-S** [comment]
@BrianHenryIE Please excuse me (a non-native English speaker) for using a wrong word. I meant to say that I really wouldn't like WordPress to[ _close_](https://wordpress.org/support/topic/what-happens-to-those-plugins-that-close-and-on-which-we-are-totally-dependent/) the plugin, like they did with for example [this one](https://wordpress.org/plugins/file-away/). 

I am aware that the plugin currently works well, and I would like very much that it keeps working as long as I've got a WordPress site to maintain. As stated in my profile, I'm not a coder, so I can't help with that (and currently that isn't even necessary), but if somebody could kindly explain to me how to [test a plugin](https://www.wpbeginner.com/opinion/should-you-install-plugins-not-tested-with-your-wordpress-version/) and where and how submit my test results, I would be willing to contribute by doing this. If I can contribute in another way, please let me know.

**Comment by jamiebergen** [comment]
Sorry for my absence. @BrianHenryIE - Thanks for chiming in! I've updated the latest WP version tested, so the "This plugin hasn’t been tested with the latest 3 major releases ..." banner is no longer there. I'll try to stay on top of this better!

**Comment by Manja-S** [comment]
Thank you @jamiebergen! I really appreciate this.
