### ISSUE TITLE
Feature request: Option to place notes in the description column

### ISSUE THREAD

**Issue by jamiebergen** [jamiebergen/plugin-notes-plus#2]
See feature request here: https://wordpress.org/support/topic/request-for-different-placement-of-notes/

"Plugin Notes places its notes in the description column, rather than adding an extra column. I find this much preferable because there is plenty of width available and it avoids widening the screen width required and deepening the height used for each plugin, as happens when there is only a narrow space available in the extra column. I also liked the way Plugin Notes coloured the background to make the notes stand out, although the method of selecting the colour by hex code was very poor to use.

Please consider the alternative placement, either as a change or option. I can supply examples or copy of the code if required. Thanks."

**Comment by ccollabgist** [comment]
Just dropping a note to say we'd love to see different placements get added as well; preferably beneath the description vs. its own column.

Thanks for making/maintaining this plugin since the one we used previously is no longer available!

**Comment by antipole2** [comment]
I would love to see this and the colour option implemented.  I know time can be short but just to say long forward to being able to change over from the old plugin.  Thanks in hope!

**Comment by antipole2** [comment]
Any news on this, please?  I need to switch over from Plugin Notes as it will fail on the next PHP version but this issue of note placement is a serious one.
Lot's of accolades waiting for an update!

**Comment by antipole2** [comment]
Still longing for the notes to be displayed in the description column rather than in its own or at least that as an option.  Pleeeease can someone make this available!

**Comment by jamiebergen** [comment]
I've just released an update (version 1.2.4) that gives users an option to move notes to the description column. See the README FAQ for the code snippet to enable that option.
